/* Single local account, NTLMv2 over SPNEGO. See MS-NLMP sections
 * 2.2.1, 3.2.5.2 and 3.3.2, and RFC 4178. No LM/NTLMv1 fallback.
 * Credentials deliberately use printable ASCII (password up to 256 bytes,
 * username up to 64); filename encoding is handled separately. */
#include "smbd.h"
#include <sys/file.h>
#include <fcntl.h>

#define N_UNICODE 0x00000001UL
#define N_SIGN 0x00000010UL
#define N_NTLM 0x00000200UL
#define N_EXTENDED 0x00080000UL
#define N_VERSION 0x02000000UL
#define N_KEYEXCH 0x40000000UL
#define N_SUPPORTED 0xe2088215UL

static int random_fd = -1;
static int random_pool;
static u8 ntlm_oid[12]={0x06,0x0a,0x2b,0x06,0x01,0x04,0x01,0x82,0x37,0x02,0x02,0x0a};
static u8 ntlm_magic[8]={'N','T','L','M','S','S','P',0};

static void wipe(p,n)
void *p;
unsigned n;
{
 volatile u8 *q;
 q=(volatile u8 *)p;
 while(n--) *q++=0;
}
static int private_file(fd)
int fd;
{
 struct stat st;
 return fstat(fd,&st)==0 && (st.st_mode&S_IFMT)==S_IFREG &&
  (st.st_mode&077)==0 && st.st_uid==geteuid() && st.st_nlink==1;
}
static int unhex(c)
unsigned c;
{
 if(c>='0' && c<='9') return c-'0';
 if(c>='a' && c<='f') return c-'a'+10;
 if(c>='A' && c<='F') return c-'A'+10;
 return -1;
}
int auth_load()
{
 int fd,r,ok,a,b;
 unsigned n,i;
 u8 password[258],pair[2],extra;
 struct hashctx h;
 wipe(cfg.nthash,16);
 if(cfg.guest) return 1;
 if(!cfg.user || (!cfg.password_file && !cfg.hash_file) ||
    (cfg.password_file && cfg.hash_file)) return 0;
 n=(unsigned)strlen(cfg.user);
 if(n==0 || n>64) return 0;
 for(i=0;i<n;i++) if((u8)cfg.user[i]<33 || (u8)cfg.user[i]>126) return 0;
 fd=open(cfg.hash_file?cfg.hash_file:cfg.password_file,O_RDONLY);
 if(fd<0) return 0;
 if(!private_file(fd)) { close(fd); return 0; }
 n=0; ok=1;
 while(n<sizeof(password)) {
  r=read(fd,password+n,sizeof(password)-n);
  if(r<0 && errno==EINTR) continue;
  if(r<0) { ok=0; break; }
  if(r==0) break;
  n+=(unsigned)r;
 }
 if(n==sizeof(password)) {
  do { r=read(fd,&extra,1); } while(r<0 && errno==EINTR);
  if(r!=0) ok=0;
 }
 close(fd);
 if(n && password[n-1]=='\n') {
  n--; if(n && password[n-1]=='\r') n--;
 } else if(!cfg.hash_file && n && password[n-1]=='\r') n--;
 if(cfg.hash_file) {
  if(n!=32) ok=0;
  if(ok) for(i=0;i<16;i++) {
   a=unhex(password[i*2]); b=unhex(password[i*2+1]);
   if(a<0 || b<0) { ok=0; break; }
   cfg.nthash[i]=(u8)((a<<4)|b);
  }
 } else {
  if(n==0 || n>256) ok=0;
  for(i=0;i<n;i++) if(password[i]<32 || password[i]>126) ok=0;
  if(ok) {
   hash_init(&h,4); pair[1]=0;
   for(i=0;i<n;i++) { pair[0]=password[i]; hash_update(&h,4,pair,2); }
   hash_final(&h,4,cfg.nthash);
  }
 }
 if(!ok) wipe(cfg.nthash,16);
 wipe(password,sizeof(password)); wipe(pair,sizeof(pair)); wipe(&extra,1); wipe(&h,sizeof(h));
 return ok;
}

/* A target random pool contains bytes generated by a cryptographic RNG on
 * a trusted modern host. Lock it for this listener's lifetime, overwrite
 * each challenge before use, then fsync: restarts cannot replay challenges.
 * Reusing a backup/copy of a consumed pool is forbidden. */
int auth_random_init()
{
 if(cfg.guest) return 1;
 random_pool=cfg.random_file!=0;
#ifdef PDP11
 if(!random_pool) return 0;
#endif
 random_fd=open(random_pool?cfg.random_file:"/dev/urandom",random_pool?O_RDWR:O_RDONLY);
 if(random_fd<0) return 0;
 if(random_pool && (!private_file(random_fd) || flock(random_fd,LOCK_EX|LOCK_NB)<0)) {
  close(random_fd); random_fd=-1; return 0;
 }
 return 1;
}
void auth_random_close()
{
 if(random_fd>=0) close(random_fd);
 random_fd=-1;
}
int auth_random_challenge()
{
 u8 zero[8];
 unsigned n;
 int r;
 off_t pos;
 memset(zero,0,sizeof(zero));
 if(cfg.guest) { memset(auth.challenge,0,8); return 1; }
 if(random_fd<0) return 0;
 for(;;) {
  pos=0;
  if(random_pool) { pos=lseek(random_fd,0L,1); if(pos<0) return 0; }
  n=0;
  while(n<8) {
   r=read(random_fd,auth.challenge+n,8-n);
   if(r<0 && errno==EINTR) continue;
   if(r<=0) { wipe(auth.challenge,8); return 0; }
   n+=(unsigned)r;
  }
  if(!random_pool) return 1;
  if(constant_equal(auth.challenge,zero,8)) continue;
  if(lseek(random_fd,pos,0)<0) { wipe(auth.challenge,8); return 0; }
  n=0;
  while(n<8) {
   r=write(random_fd,zero+n,8-n);
   if(r<0 && errno==EINTR) continue;
   if(r<=0) { wipe(auth.challenge,8); return 0; }
   n+=(unsigned)r;
  }
  if(fsync(random_fd)<0) { wipe(auth.challenge,8); return 0; }
  return 1;
 }
}

/* DER lengths are bounded before addition; no indefinite length encoding.
 * Descend only into ASN.1 constructed values, not arbitrary octet payloads. */
static int unwrap(p,n,depth,found,found_n)
const u8 *p;
unsigned n,depth;
const u8 **found;
unsigned *found_n;
{
 unsigned h,len,tag,k,j;
 if(depth>8) return 0;
 while(n) {
  if(n<2) return 0;
  tag=p[0]; len=p[1]; h=2;
  if(len&128) {
   k=len&127; if(k==0 || k>2 || n<2+k) return 0;
   len=0;
   for(j=0;j<k;j++) len=(len<<8)|p[h++];
   if(len<128) return 0;
  }
  if(h>n || len>n-h) return 0;
  if(tag==4 && len>=12 && memcmp(p+h,ntlm_magic,8)==0) {
   if(*found) return 0;
   *found=p+h; *found_n=len;
  } else if(tag&32) {
   if(!unwrap(p+h,len,depth+1,found,found_n)) return 0;
  }
  p+=h+len; n-=h+len;
 }
 return 1;
}
static void shift_right(p,n,count)
u8 *p;
unsigned n,count;
{
 while(n) { n--; p[n+count]=p[n]; }
}
static unsigned der_wrap(p,tag,n)
u8 *p;
unsigned tag,n;
{
 unsigned h;
 h=n<128?2:(n<256?3:4);
 shift_right(p,n,h); p[0]=(u8)tag;
 if(h==2) p[1]=(u8)n;
 else if(h==3) { p[1]=0x81; p[2]=(u8)n; }
 else { p[1]=0x82; p[2]=(u8)(n>>8); p[3]=(u8)n; }
 return n+h;
}
unsigned auth_negotiate(out)
u8 *out;
{
 static u8 initial[30]={0x60,0x1c,0x06,0x06,0x2b,0x06,0x01,0x05,
  0x05,0x02,0xa0,0x12,0x30,0x10,0xa0,0x0e,0x30,0x0c,
  0x06,0x0a,0x2b,0x06,0x01,0x04,0x01,0x82,0x37,0x02,0x02,0x0a};
 memcpy(out,initial,sizeof(initial)); return sizeof(initial);
}
static unsigned wrap_challenge(out,n)
u8 *out;
unsigned n;
{
 u8 prefix[19];
 n=der_wrap(out,4,n); n=der_wrap(out,0xa2,n);
 prefix[0]=0xa0; prefix[1]=3; prefix[2]=0x0a; prefix[3]=1; prefix[4]=1;
 prefix[5]=0xa1; prefix[6]=12; memcpy(prefix+7,ntlm_oid,12);
 shift_right(out,n,19); memcpy(out,prefix,19); n+=19;
 n=der_wrap(out,0x30,n); return der_wrap(out,0xa1,n);
}
static void secbuf(p,n,offset)
u8 *p;
unsigned n,offset;
{
 put16(p,n); put16(p+2,n); put32(p+4,(u32)offset);
}
static unsigned avname(p,id,name)
u8 *p;
unsigned id;
const char *name;
{
 unsigned n;
 n=utf16_encode(p+4,name,128); put16(p,id); put16(p+2,n); return n+4;
}
static u32 challenge(p,n,out,out_n)
const u8 *p;
unsigned n;
u8 *out;
unsigned *out_n;
{
 u32 flags;
 unsigned k,target,info,i;
 char hostname[64];
 if(n<32 || n>sizeof(auth.negotiate)) return ST_INVALID;
 flags=get32(p+12);
 if((flags&(N_UNICODE|N_NTLM|N_EXTENDED))!=(N_UNICODE|N_NTLM|N_EXTENDED)) return ST_NOT_SUPPORTED;
 flags=(flags&N_SUPPORTED)|0x00828005UL; /* target info, server, always sign */
 if(!(flags&N_SIGN)) flags&=~N_KEYEXCH;
 memcpy(auth.negotiate,p,n); auth.negotiate_len=n;
 memset(out,0,512); memcpy(out,ntlm_magic,8); put32(out+8,2UL);
 put32(out+20,flags); memcpy(out+24,auth.challenge,8);
 if(flags&N_VERSION) { out[48]=6; out[49]=1; put16(out+50,7601); out[55]=15; }
 k=56; target=k; k+=utf16_encode(out+k,"PDP11",128); secbuf(out+12,k-target,target);
 info=k; k+=avname(out+k,1,"PDP11"); k+=avname(out+k,2,"WORKGROUP");
 memset(hostname,0,sizeof(hostname));
 if(gethostname(hostname,sizeof(hostname)-1)<0) strcpy(hostname,"pdp11");
 for(i=0;hostname[i];i++) if((u8)hostname[i]<33 || (u8)hostname[i]>126) { strcpy(hostname,"pdp11"); break; }
 if(!hostname[0]) strcpy(hostname,"pdp11");
 k+=avname(out+k,3,hostname);
 put16(out+k,7); put16(out+k+2,8); filetime(out+k+4,(long)time((time_t *)0)); k+=12;
 put16(out+k,0); put16(out+k+2,0); k+=4;
 secbuf(out+40,k-info,info);
 memcpy(auth.challenge_msg,out,k); auth.challenge_len=k;
 *out_n=wrap_challenge(out,k); auth.phase=1;
 return ST_MORE_AUTH;
}
static int field(p,n,at,ptr,len,min)
const u8 *p;
unsigned n,at,min;
const u8 **ptr;
unsigned *len;
{
 u32 off;
 *len=get16(p+at); off=get32(p+at+4);
 if(off>(u32)n || (u32)*len>(u32)n-off || (*len && off<(u32)min)) return 0;
 *ptr=p+(unsigned)off; return 1;
}
static u8 upper(c)
u8 c;
{
 return c>='a' && c<='z'?(u8)(c-'a'+'A'):c;
}
static void rc4_16(key,in,out)
const u8 *key,*in;
u8 *out;
{
 u8 s[256],t;
 unsigned i,j,k;
 for(i=0;i<256;i++) s[i]=(u8)i;
 j=0;
 for(i=0;i<256;i++) { j=(j+s[i]+key[i&15])&255; t=s[i]; s[i]=s[j]; s[j]=t; }
 i=j=0;
 for(k=0;k<16;k++) {
  i=(i+1)&255; j=(j+s[i])&255; t=s[i]; s[i]=s[j]; s[j]=t;
  out[k]=in[k]^s[(s[i]+s[j])&255];
 }
 wipe(s,sizeof(s));
}
static u32 auth_reject(reason)
const char *reason;
{
 if(cfg.verbose) fprintf(stderr,"smbd: NTLMv2 rejected: %s\n",reason);
 return ST_LOGON_FAILURE;
}
static u32 authenticate(p,n,out,out_n)
const u8 *p;
unsigned n;
u8 *out;
unsigned *out_n;
{
 const u8 *nt,*user,*domain,*encrypted,*unused;
 const char *reason;
 unsigned nt_n,user_n,domain_n,encrypted_n,unused_n,i,off,len,id,mic_at;
 int mic,ended,ok;
 u32 flags,negflags;
 u8 responsekey[16],proof[16],session[16],calcmic[16],pair[2],zeros[16];
 struct hmacctx hm;
 static u8 complete[9]={0xa1,7,0x30,5,0xa0,3,0x0a,1,0};
 if(n<64 || n>4096) return ST_INVALID;
 flags=get32(p+60); negflags=get32(auth.challenge_msg+20);
 mic_at=flags&N_VERSION?72:64;
 if(n<mic_at) return ST_INVALID;
 if(!field(p,n,12,&unused,&unused_n,mic_at) ||
    !field(p,n,20,&nt,&nt_n,mic_at) ||
    !field(p,n,28,&domain,&domain_n,mic_at) ||
    !field(p,n,36,&user,&user_n,mic_at) ||
    !field(p,n,44,&unused,&unused_n,mic_at) ||
    !field(p,n,52,&encrypted,&encrypted_n,mic_at)) return ST_INVALID;
 if(cfg.guest) {
  if(auth.signing_required) return ST_DENIED;
  auth.guest=1; auth.authenticated=1; auth.phase=2; memset(auth.key,0,16);
  memcpy(out,complete,9); *out_n=9; return ST_OK;
 }
 if((flags&(N_UNICODE|N_NTLM|N_EXTENDED|N_KEYEXCH|N_SIGN))!=
    (negflags&(N_UNICODE|N_NTLM|N_EXTENDED|N_KEYEXCH|N_SIGN)))
  return auth_reject("negotiated flags");
 if((user_n&1) || (domain_n&1) || user_n==0 || user_n>128 || domain_n>512 ||
    nt_n<48 || nt_n>2048) return auth_reject("credential field lengths");
 if(user_n/2!=strlen(cfg.user)) return auth_reject("account name");
 for(i=0;i<user_n;i+=2) if(user[i+1] || upper(user[i])!=upper((u8)cfg.user[i/2]))
  return auth_reject("account name");
 /* NTLMv2 version and all fixed reserved fields. Reject NTLMv1 outright. */
 if(nt[16]!=1 || nt[17]!=1 || get16(nt+18)!=0 || get32(nt+20)!=0 || get32(nt+40)!=0)
  return auth_reject("NTLMv2 response format");
 /* AV_PAIR list begins 28 bytes into the client challenge. */
 off=44; mic=0; ended=0;
 while(off+4<=nt_n) {
  id=get16(nt+off); len=get16(nt+off+2); off+=4;
  if(len>nt_n-off) return ST_INVALID;
  if(id==0) { if(len) return ST_INVALID; ended=1; break; }
  if(id==6) { if(len!=4) return ST_INVALID; if(get32(nt+off)&2UL) mic=1; }
  off+=len;
 }
 if(!ended) return ST_INVALID;
 if(mic) {
  if(n<mic_at+16) return ST_INVALID;
  for(i=12;i<=52;i+=8) {
   if(get16(p+i) && get32(p+i+4)<(u32)(mic_at+16)) return ST_INVALID;
  }
 }
 hmac_init(&hm,5,cfg.nthash,16); pair[1]=0;
 for(i=0;i<user_n;i+=2) { pair[0]=upper(user[i]); hmac_update(&hm,pair,2); }
 hmac_update(&hm,domain,domain_n); hmac_final(&hm,responsekey);
 hmac_init(&hm,5,responsekey,16); hmac_update(&hm,auth.challenge,8);
 hmac_update(&hm,nt+16,nt_n-16); hmac_final(&hm,proof);
 ok=constant_equal(proof,nt,16); reason="NTLMv2 proof";
 if(ok) {
  reason="session key format";
  hmac_init(&hm,5,responsekey,16); hmac_update(&hm,nt,16); hmac_final(&hm,session);
  if(negflags&N_KEYEXCH) {
   if(encrypted_n!=16) ok=0;
   else rc4_16(session,encrypted,auth.key);
  } else {
   if(encrypted_n!=0) ok=0;
   memcpy(auth.key,session,16);
  }
 }
 if(ok && mic) {
  reason="message integrity check";
  memset(zeros,0,16); hmac_init(&hm,5,auth.key,16);
  hmac_update(&hm,auth.negotiate,auth.negotiate_len);
  hmac_update(&hm,auth.challenge_msg,auth.challenge_len);
  hmac_update(&hm,p,mic_at); hmac_update(&hm,zeros,16);
  hmac_update(&hm,p+mic_at+16,n-mic_at-16); hmac_final(&hm,calcmic);
  ok=constant_equal(calcmic,p+mic_at,16);
 }
 wipe(responsekey,16); wipe(proof,16); wipe(session,16); wipe(calcmic,16);
 wipe(pair,2); wipe(&hm,sizeof(hm));
 if(!ok) { wipe(auth.key,16); return auth_reject(reason); }
 auth.authenticated=1; auth.phase=2; auth.guest=0;
 memcpy(out,complete,9); *out_n=9;
 return ST_OK;
}
u32 auth_session(in,n,out,out_n)
const u8 *in;
unsigned n;
u8 *out;
unsigned *out_n;
{
 const u8 *p;
 unsigned len;
 u32 result;
 *out_n=0; p=0; len=0;
 if(n<12 || n>4096 || auth.authenticated || auth.phase>1) return ST_INVALID;
 if(memcmp(in,ntlm_magic,8)==0) { p=in; len=n; }
 else if(!unwrap(in,n,0,&p,&len) || !p) return ST_NOT_SUPPORTED;
 if(get32(p+8)==1 && auth.phase==0) return challenge(p,len,out,out_n);
 if(get32(p+8)!=3 || auth.phase!=1) return ST_INVALID;
 result=authenticate(p,len,out,out_n);
 /* A consumed challenge can never authenticate a second attempt. */
 if(result!=ST_OK) { auth.phase=3; auth.authenticated=0; wipe(auth.key,16); }
 return result;
}
